### ISSUE TITLE
Array vs List

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-jordans-reference#126]
Storing this for later:

> hello. when should I use `Array` and when `List`?

> It depends on which operations you want to do. Any update on an array is Ө(n) but random lookup is O(1). Lists have efficient operations at the front, and everything else is O(n). Array updates copy all other elements, resulting in twice the memory usage, while for most list operations the result and the source share part of the list. However, lists use a less compact layout in memory.
> Rules of thumb: if you create the sequence one and read it many times, use an array. Folds over arrays are faster, length is constant time and lookup is constant time. If you want to constantly manipulate the structure, especially at the front, use a list.
> If your number of elements is very small (i.e. n is bounded), try both and measure. Array might in many cases be faster for few elements, even with random updates. Mostly because cloning of arrays is implemented directly in V8, whereas rebuilding lists is done with many many PureScript operations.

**Comment by JordanMartinez** [comment]
Hm... I'm not really sure where this should go...

**Comment by razcore-rad** [comment]
I think this might be a good candidate for `Design Patterns` since this is what they are, data type patterns for solving a problem. The problem of a chain of data linked somehow and each has pros and cons, just like every other pattern out there. Maybe this can help in identifying some categories: http://interactivepython.org/runestone/static/pythonds/index.html. It doesn't really include array talk if I remember right, cause it's a beginner book so it only uses the built-in lists. Anyway, I think it builds up nicely from one concept to the next and could serve as a guideline of sorts.
