### ISSUE TITLE
Consider having a list of research articles

### ISSUE THREAD

**Issue by razcore-rad** [JordanMartinez/purescript-jordans-reference#143]
## Context

1. Indicate the affected section (i.e. top-level folder)
Perhaps separately

2. Indicate what kind of issue this is
Enhancement = a new idea that can be documented/filed

## Body

While browsing your issues I see you refer to a lot of articles about haskell, FP, OOP etc. in general. I think it would be really useful to create an extra document that compiles all these research links together. Since if you want to understand say the reasoning behind your research or follow the thread you'll probably end up searching Google and ending up to those same articles anyway, or similar ones. It's not immediately obvious that searching through issues you'll find all these cool articles, and who wants to search for them anyway? Wouldn't we rather have a list? :)

**Comment by JordanMartinez** [comment]
I'm not quite understanding you for one reason. Are you referring to issues specifically marked with "helpful links"? Or are you referring to the numerous links inside of this repo's Markdown files.

If the first, that's a good idea. Sometimes, I come across articles that I think would be useful/helpful but don't know where to put them yet. At the same time, I try not to link to every possible FP article. Some explain X very clearly and concisely. Others take forever to get to a point, or I gain a clue from it but the concept is still a mystery to me afterwards. Finally, others are academic papers that are sometimes best summarized since they take too long to read through for most people.

If the second one, I think the most central and useful area for this is [here](https://github.com/JordanMartinez/purescript-jordans-reference/tree/latestRelease/21-Hello-World#other-learning-resources). For example, the "What I Wish I Knew When Learning Haskell" is similar to some aspects of this repo but for Haskell. 

However, maintenance also comes to mind. For right now, I'm using a very low maintenance approach. I can use GitHub's own search bar to search this repo or even use Atom's Project search to find specific things, which tends to be better than GitHub.

**Comment by razcore-rad** [comment]
Not only the issues specifically marked with "helpful links", just issues
in general, say as an example the link from #129. I know some links aren't
useful and I thought you might say something about wanting to keep it low
maintenance. So I thought of something, what if we come up with a way to
present these links in an easy way to get parsed. Say a line like this:

`LINK[1]: actual_link, description`
or
`LINK[category]: actual_link, name, description`

This way we could then build a tool to parse the issues and gather the
links for us, sort them by categories or other criteria, potentially flag
them as not so concise - dive at your own risk - DAYOR :) - etc.

**Comment by JordanMartinez** [comment]
Makes sense and I like the idea.

Let's first define things using the GTD methodology

Purpose: to provide a resource for all links used in this repo

Principles
- centralized location for easier access
- low-maintenance 
    - easy to add/change/remove links)
    - maintainer runs some script/program and "it's done, no questions asked."
- easy to parse (i.e. well-defined syntax/language/format for links)
- links should be categorized by
    - expected read time
    - tags based on its main or related concepts
    - usefulness of the link
    - difficulty of the link's reading (beginner, intermediate, advance, etc.)
    - other content-based tags (has pictures, has code, has animation, has video, etc.)
- links should not reduce the readability of content (if, for example, the parsable-data of the link appears immediately after a link is referenced in some page and it's like 10 lines long; in other words, it should appear at the end of the page if possible)

Outcome
- user can find content by tags

Brainstorm
- test the program
- write it
- define a spec for the language of the link data and how it integrates with this repo
    - determine whether this would best be done via a page in this repo that is generated by a program or via a program that handles this separately

**Comment by JordanMartinez** [comment]
I'm closing this issue for now as being "out of the scope of this project," but might reopen it later. There are a few places that already do this somewhat:
- [awesome-functional-programming](https://github.com/lucasviola/awesome-functional-programming#readme)
- [awesome-fp-js](https://github.com/stoeffel/awesome-fp-js#readme)
