### ISSUE TITLE
Document "Backend questions" for C backend

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-jordans-reference#145]
I'd like to include documentation in my learning repo that helps one understand the minimum knowledge needed to work with various backends for PureScript. 

For example, if I only programmed in Javascript, then discovered Purescript, got familiar with it, and then wanted to write a program in C using PureScript, I may be very familiar with Javascript, but C is a labyrinth. There are some things I would need to know before I could write even a Hello World in C:
1. Does the C backend require anything to be installed on my computer (e.g. `gcc`)? For a Javascript one, I really only need Node.js via npm
2. What does FFI with a C backend look like? For Javascript, I can refer to the contents of this folder: https://github.com/JordanMartinez/purescript-jordans-reference/tree/latestRelease/11-Syntax/02-Foreign-Function-Interface/src)
3. What types does a C backend have that other backends don't, that it shares with some but not all backends, and that it shares with all backends?

This should be done for other backends as well (e.g. Swift).

**Comment by JordanMartinez** [comment]
As for where things should go:
1. It should appear in the `Getting Started/Backends/C.md` file.
2. It should appear in the `Syntax/FFI/Backends/C/` folder
3. It should appear in the `Syntax/Basic Syntax/Backends/C/` folder. This will be a breaking change since it will require splitting the Javascript and C backends. (#131)

**Comment by razcore-rad** [comment]
Or you could make different branches, or possibly have JavaScript as "the default" and all others in the `Backends` folders

**Comment by JordanMartinez** [comment]
> Or you could make different branches, or possibly have JavaScript as "the default" and all others in the Backends folders

Um.... I'm going to say a hard no. Most of the content in this repo will work for all backends because a backend merely defines the actual runtime to which PureScript compiles. Thus, there's no reason that I can think of to keep multiple branches, as that would force a maintainer to keep them all in sync. I think it makes more sense to have separate folders for specific concepts that are runtime-specific. 

Also, how one would handle releases? `ps-0.12.x-v0.9.8-javascript`? Ew...

Feel free to disagree with me as you may see something I don't and I would welcome such a perspective.

**Comment by razcore-rad** [comment]
Right, reading my comment I don't think I was clear on the second part. What I meant by <<have JavaScript as "the default" and all others in the `Backends` folders>> is not related to branches but just a structure of the repository in which the "main/default" backend is JavaScript (the root directory of `Syntax`, `HelloWorld` etc.) and have then notes on other backends in a `Backends` directory within those folders. This reasoning comes from something like GodotEngine's philosophy. In the docs the "main" supported version of the docs is for `GDScript` (they're own little scripting language), whereas the examples in the other languages (say `C#`) are mostly provided by the community if they want to get involved.

Since 95-99% of the things aren't backend related in this repository, I'm thinking that "extra notes on other backends" or something like that, possibly "differences from javascript backend" should suffice.

Now that you mention it, I agree, the idea to have multiple branches isn't very good.

**Comment by JordanMartinez** [comment]
How's this structure for this repo?

```
Getting Started/ReadMe.md - includes a note about the different backends for Purescript
Build Tools/Other Backends/* - separate build tools for each backend into its own folder with Javascript as the main one

// because we want the syntax to be verified by compilation,
// we need each backend to have its own `src` folder
// Thus, these intro files would appear first
Syntax/Value Function Data Syntax.purs
Syntax/Explaining Kinds.md

// Then, each backend's Prim module here
Syntax/Prim-Module-Javascript.purs
Syntax/Prim-Module-C-Backend.purs

// Then, the shared PS stuff between them would
// appear as we have it now, defaulting
// to the Javascript backend
Syntax/Basic Syntax/Purescript/src/** - what's in the `src` folder right now

// Hello World should still work as long as we indicate what
// the corresponding C-backend library is for some js-backend library
// in one file. (e.g. what is the `purescript-effect` library
// for the C-backend?)
Hello World/** - Provide a mapping from js-backend PS libraries to their other-backend PS libraries (e.g. Prelude)
```

**Comment by JordanMartinez** [comment]
After more thought, I'm going to close this. I think each backend should cover these kind of questions themselves.
