### ISSUE TITLE
Clarify numbering system - [theme][concept]

### ISSUE THREAD

**Issue by aniketd** [JordanMartinez/purescript-jordans-reference#200]
Section:
  Syntax
Issue Type:
  Bug, perhaps.
Folder/File(s):
  Syntax/Basic Syntax/src/Data and Functions/

There is a chapter-or-file missing at number 10.
There is 09-Records, and there is 11-Infix-Notation. There is no 10-*.

NOTE: Just to clarify, I'm opening this issue so that, if there is a chapter no. 10. and somehow it got left out, this might help. A missing serial number does feel strange.

**Comment by JordanMartinez** [comment]
@aniketd Thanks for opening this issue.

Actually, this is purely intentional. I generally see the file numbers in this light:
[major theme/idea][minor idea]
01 = first major theme, first minor idea
02 = first major theme, second minor idea
11 = second major theme, first minor idea

I don't think there is ever a time where I actually go beyond 10 in one major theme. In such situations, I'll usually create a folder instead.

So, I think the real issue here is just clarifying that in the project's ReadMe.

**Comment by aniketd** [comment]
@JordanMartinez Thanks for clarifying! And much thanks for this repo! :)

**Comment by JordanMartinez** [comment]
You're welcome! And I'd recommend reading from the `v0.10` branch until it gets merged into `latestRelease` as I'm correcting a lot of MTL/Free stuff that I initially misunderstood.

**Comment by JordanMartinez** [comment]
Closed by #202
