### ISSUE TITLE
Design Pattern: In GADT, why is purescript-leibniz used instead of purescript-type-equality?

### ISSUE THREAD

**Issue by dlight** [JordanMartinez/purescript-jordans-reference#336]
Well I'm sad that Purescript doesn't have equality constraints (I wonder why is that).

The [GADT approximation](http://code.slipthrough.net/2016/08/10/approximating-gadts-in-purescript/) that `Design-Patterns/GADTs.md` links reifies equality constraints at the value level (so people has to juggle around values of `Leibniz` type). But why not use [`purescript-type-equality`](https://github.com/purescript/purescript-type-equality)?

**Comment by JordanMartinez** [comment]
> Well I'm sad that Purescript doesn't have equality constraints (I wonder why is that).

I'm not entirely sure what 'equality constraints' are, but I know PS doesn't have 'constraint kinds.' It's a feature on the to-do list for core contributors, but it hasn't been done because it's a breaking change. There's also been talk about the 'zero-cost coercible' idea in one of their issues.

> The GADT approximation that Design-Patterns/GADTs.md links reifies equality constraints at the value level (so people has to juggle around values of Leibniz type). But why not use purescript-type-equality?

The article (based on its URL and comparing that to the Internet Archive) was written on August 8, 2016. I don't think it was ever updated since then. Meanwhile, the first commit for `type-equality` was on [October 8, 2016](https://github.com/purescript/purescript-type-equality/commit/07a3879789ece75e87c4be39e40fb0b16b9a6ac3). 
So that might be why the article itself doesn't explain how it differs.

As for your actual question, I imagine that using `type equality` would be slower because you're passing around type class dictionaries, but a benchmark would have more weight. Looking at `Leibniz`'s source code more, it seems like it's better when higher-kinded data types are used, but I'm not actually sure.

Also, I got the following code to compile:
```purescript
import Prelude

import Data.Leibniz (type (~))
import Type.Equality (class TypeEquals)

-- Leibniz type
data ExprL a
  = L_Add (ExprL Int) (ExprL Int) (a ~ Int)
  | L_Mult (ExprL Int) (ExprL Int) (a ~ Int)
  | L_Equal (ExprL Int) (ExprL Int) (a ~ Boolean)
  | L_Not (ExprL Boolean) (a ~ Boolean)
  | L_Val Int (a ~ Int)

data Expr a
  = Add (Expr Int) (Expr Int) (TypeEquals a Int => a)
  | Mult (Expr Int) (Expr Int) (TypeEquals a Int => a)
  | Equal (Expr Int) (Expr Int) (TypeEquals a Boolean => a)
  | Not (Expr Boolean) (TypeEquals a Boolean => a)
  | Val Int (TypeEquals a Int => a)
```

**Comment by JordanMartinez** [comment]
I haven't heard a response back, so I'm closing this.
