### ISSUE TITLE
Table of Contents / Breadcrumbs

### ISSUE THREAD

**Issue by dakom** [JordanMartinez/purescript-jordans-reference#43]
Would be lovely to have a way of navigating around all the content, as well as knowing where I left off.

Great work btw!

**Comment by JordanMartinez** [comment]
Yeah... That's easier to do if the links would never change though (changing a file's numerical order and all links to it are immediately broken). Perhaps when I finish a stable version that would make sense? For me, it's easier just to `git clone` this repo and read it locally...

**Comment by JordanMartinez** [comment]
Just filing this thought for later. 

While a "bread crumbs" idea would be nice, it will be harder to track things down because one would have to go through many files to update things. Having a single Table of Contents file would make maintaining this much easier.

Also, I think the "Table of Contents" file should be written in Asciidoc. Markdown's numbered lists force you to write the number each time, making it annoying when one reorders things. Asciidoc's syntax for doing the same thing allows you to reorder it however you want and the output will be correct, making it easier to reorder things.

Lastly, perhaps this should be a program that we write in this project: a program that can read all the files, determine what their header/sections are, and generate an Asciidoc/Markdown file that guarantees that the links work correctly and aren't broken? It could be released separately from this project to have a different license than this one.

**Comment by JordanMartinez** [comment]
Somewhat related to this: https://github.com/thlorenz/doctoc

**Comment by JordanMartinez** [comment]
@dakom See #222

**Comment by dakom** [comment]
Cool! Haven't been touxhing purescript lately but it's great to know this resource is there when I need it. Thanks for the reminder!

**Comment by JordanMartinez** [comment]
I'm not going to close this yet as I'm stilling finishing up #222. However, @dakom, you can see the current work in [table-of-contents.md](https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/table-of-contents.md).

Forewarning: the links all point to the `developer` branch, not the `latestRelease` branch. I also don't yet guarantee that all links work correctly.

**Comment by JordanMartinez** [comment]
I'd say for now that this issue is closed. There's still some more work I want to do on it (like figure out how to create a ToC using tags rather than branch names), but it's good enough for now. Those other issues can be worked out separately.
