### ISSUE TITLE
Typo and question

### ISSUE THREAD

**Issue by toraritte** [JordanMartinez/purescript-jordans-reference#497]
## Context

1. **Section**:   Getting Started

2. **Issue Type**: bug

3. **Folder/file(s)**: [Getting Started/The REPL.md#show](https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/00-Getting-Started/03-The-REPL.md#show)

## Body

> ### Show
>
>There are two commands in this one:

1. > - `show loaded`/`:s loaded` - Shows all modules which you can import into the REPL.

     Isn't this command only showing the modules that are already loaded?

2. > - `show import`/`:s imported` - Shows which modules you currently have imported in the REPL

    It should say `:s import`. (Although, it would be indeed more consistent if the REPL option would say `imported`.)

Thank you for all your time and effort creating and maintaining this resource!

**Comment by JordanMartinez** [comment]
> Isn't this command only showing the modules that are already loaded?

Before running `purs repl` / `spago repl`, the compiler will compile all PS files it knows of via the source globs. These are what show up in the `:show loaded` output. However, none of them are imported yet into the REPL session, so you can't use any of them (e.g. `Data.Foldable (foldl)`).

My current rendering explains the latter point (these are what you can import) but not the part you bring up (these have been compiled, so that `purs repl` is aware of them).

> It should say :s import.

Yup, that's a typo!

**Comment by toraritte** [comment]
Thanks a lot for the explanation!
