### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by ursi** [JordanMartinez/purescript-jordans-reference#514]
https://github.com/JordanMartinez/purescript-jordans-reference/blob/d7b806061b4f67db2f59a6742f1d1e37a209345a/11-Syntax/03-Type-Level-Programming-Syntax/src/02-Basic-Syntax/10-Conventions.purs#L18
I'm not super comfortable with this stuff yet, so I'm not sure what the correct terminology would even be, but I have a strong feeling this (`value-level type`) isn't it. If it is, could you point me to the spot in the documentation that demonstrates this, thanks :)

**Comment by JordanMartinez** [comment]
Two thoughts. First, based on [this overview of the different Proxy types](https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/41-Ecosystem/Type-Level-Programming/Libraries-and-Example-Projects.md#type-level-types-values-and-proxies), it should probably read "type-level type" (i.e. Kind).

Second, once PureScript `v0.14.0` is released, it won't matter as much as we can define a single `Proxy` type that works with all kinds due to Nate's PolyKinds PR.

**Comment by ursi** [comment]
> Second, once PureScript v0.14.0 is released, it won't matter as much as we can define a single Proxy type that works with all kinds due to Nate's PolyKinds PR.

ooo exiting!

**Comment by JordanMartinez** [comment]
See the [ps-0.14](https://github.com/JordanMartinez/purescript-jordans-reference/tree/latestRelease/11-Syntax/03-Type-Level-Programming-Syntax/ps-0.14) folder in the TLP syntax folder. That folder will replace the current `src` folder once the release is made. That folder's code compiled on PS `master` when I updated it.

**Comment by ursi** [comment]
I started to look into it and then I realized I'm investing time into something that could be far enough away that I'll have to do it all over again when it actually come out, so I stopped lol
